name: Deploy to controller

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy container on controller
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 228
          script: |
            set -e
            cd /root/web-app
            git pull
            docker build -t web-app .
            docker rm -f web-app || true
            docker run -d --name web-app -p 8080:8000 web-app
